# Generated by Django 5.2.7 on 2025-10-11 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThinkShare_app', '0002_alter_comment_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='Value',
            new_name='value',
        ),
        migrations.AlterField(
            model_name='vote',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='ThinkShare_app.article'),
        ),
    ]
