# Generated by Django 5.2.7 on 2025-10-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThinkShare_app', '0003_rename_value_vote_value_alter_vote_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
