# Generated by Django 5.2.7 on 2025-10-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThinkShare_app', '0005_contact_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
