# Generated by Django 5.2.7 on 2025-10-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThinkShare_app', '0006_alter_article_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='sent_at',
            new_name='send_at',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='content',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
